<?php
/**
 * /o/_offer.php - shared template for the price-test landing pages.
 *
 * WHY THIS EXISTS
 * Meta ad comments push back hard on price ("How you charging $500 for a website
 * in 2026", "Lovable is $20"). These pages test whether a lower entry price
 * converts better, and they deliberately DO NOT run the AI generator:
 *   - generation is the expensive step and the one that produces "looks like
 *     garbage" first impressions when it misses
 *   - instead we show real sites already built, and take a brief
 * The visitor presses a button, tells us what they want, and a human builds it.
 *
 * These pages are UNLISTED: noindex, disallowed in robots.txt, linked from
 * nowhere. Only people arriving from the ad should ever see them.
 *
 * Each variant is a thin wrapper in /o/<slug>/index.php that sets $WW_VARIANT
 * and includes this file. Add a variant by adding a row to $VARIANTS plus a
 * two-line wrapper directory.
 */
declare(strict_types=1);

if (!isset($WW_VARIANT)) { header('Location: /'); exit; }

require_once '/var/www/sites/trywebwiz/private/webwiz_lib.php';

// Keep these pages out of search results. The meta tag below does the same job,
// but this header is belt-and-braces AND cannot be undone by anything else:
// robots.txt is regenerated by the SeedSite SEO manager ("# Managed by SeedSite
// SEO"), which silently reverted a Disallow: /o/ line added on 2026-08-01. Do
// not rely on robots.txt to hide these pages.
header('X-Robots-Tag: noindex, nofollow, noarchive');

// ---------------------------------------------------------------------------
// Variant definitions. price_cents is the one-time build fee.
// ---------------------------------------------------------------------------
// Two axes, three cells:
//   a vs b  = PRICE    ($100 build  vs  free build)      both WITH the builder
//   b vs c  = BUILDER  (AI builder  vs  showcase only)   both free build
// Only A ever charges a build fee. B and C bill the $50/month and nothing else.
// 'builder' => true sends the visitor into the /try generator instead of
// showing the brief form.
$VARIANTS = [
    // A: $100 one-time build, WITH the builder.
    'a' => [
        'key'        => 'a',
        'builder'    => true,
        'price_cents'=> 10000,   // $100 one-time build fee
        'monthly'    => 5000,    // $50/month hosting
        'kicker'     => 'For local businesses',
        'headline'   => 'Watch your website <em>build itself</em>.',
        'sub'        => 'Type your business name and watch a real website appear in about two minutes. If you like it, it is $100 to launch, then $50/month to host and look after it.',
        'price_line' => '$100 to build',
        'price_note' => 'then $50/month for hosting &amp; care',
        'cta'        => 'Build my site now',
        'badge'      => 'Flat $100',
    ],
    // B: free build, WITH the builder. Same experience as A, no build fee -
    // that pairing is what makes a vs b a clean price test.
    'b' => [
        'key'        => 'b',
        'builder'    => true,
        'price_cents'=> 0,       // no build fee - $50/month is the whole cost
        'monthly'    => 5000,
        'kicker'     => 'For local businesses',
        'headline'   => 'Watch your website <em>build itself</em>. Free.',
        'sub'        => 'Type your business name and watch a real website appear in about two minutes. Building it costs nothing. You pay $50/month to host it, and that is the whole cost of having a website.',
        'price_line' => '$50/month',
        'price_note' => 'no build fee &mdash; the website itself is free',
        'cta'        => 'Build my site free',
        'badge'      => 'Website built free',
    ],
    // C: free build, NO builder. Showcase only, $50 today opens the account.
    'c' => [
        'key'        => 'c',
        'builder'    => false,
        'price_cents'=> 0,       // no build fee - the $50 IS month one
        'monthly'    => 5000,
        'kicker'     => 'For local businesses',
        'headline'   => 'The website is <em>free</em>. You pay for hosting.',
        'sub'        => 'A real designer builds your site for nothing, usually within 3 business days. You pay $50/month to host it and look after it, and that is the whole cost of having a website.',
        'price_line' => '$50/month',
        'price_note' => 'no build fee &mdash; the website itself is free',
        'cta'        => 'Start my free website',
        'badge'      => 'Website built free',
    ],
];

$V = $VARIANTS[$WW_VARIANT] ?? $VARIANTS['a'];

// ---------------------------------------------------------------------------
// Showcase. ONLY sites that have been looked at by a human and judged
// presentable - a bad tile here costs more than an empty grid.
// ---------------------------------------------------------------------------
$SHOWCASE = [
    ['token' => 'd1fa58b89d4ce070c8700954', 'name' => '1 Down Fence Company', 'trade' => 'Fencing contractor'],
    ['token' => 'e2f229e6240312fb9b6a3c8c', 'name' => 'Beaver Roofing',        'trade' => 'Roofing'],
    ['token' => '96e77503e68e48db16f7e9cf', 'name' => 'Ridgeline Coffee',      'trade' => 'Coffee roaster'],
];

// Record the pageview so variants can be compared on more than clicks.
try {
    $db = ww_db();
    // try_events has no 'detail' column - the variant goes in payload, matching
    // how hero_view and the rest of the /try funnel events are recorded.
    $db->prepare("INSERT INTO try_events (event, payload, ip, user_agent) VALUES ('offer_view', ?, ?, ?)")
       ->execute([
           json_encode(['variant' => $V['key'], 'from' => $_SERVER['HTTP_REFERER'] ?? null], JSON_UNESCAPED_SLASHES),
           substr((string)($_SERVER['REMOTE_ADDR'] ?? ''), 0, 45),
           substr((string)($_SERVER['HTTP_USER_AGENT'] ?? ''), 0, 300),
       ]);
} catch (Throwable $e) { /* never let analytics break the page */ }

$ver = defined('WW_VERSION') ? WW_VERSION : '0';
?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Unlisted price test. Must never be indexed or linked publicly. -->
<meta name="robots" content="noindex, nofollow, noarchive">
<title>Websites for local businesses &middot; WebWiz</title>
<meta name="description" content="A real designer builds your website. See real examples and tell us what you want.">
<link rel="icon" href="/favicon.ico">
<?php
// Meta Pixel + CAPI, reusing the same bootstrap /try uses (pixel 1974530180093513).
// This gives us window.wwMetaTrack(), which fires the browser pixel AND posts to
// /api/capi.php with a shared eventID so the two are deduplicated. Rolling our
// own fbq() call here would have produced double-counted, unattributed events.
@require_once '/var/www/sites/trywebwiz/public/api/_meta.php';
if (function_exists('ww_meta_pixel_base_html')) { echo ww_meta_pixel_base_html(); }
?>
<script src="/api/sentry.js.php" defer></script>
<style>
  :root{
    --cream:#FAF5EA; --navy:#12184A; --teal:#12A594; --yellow:#FFC83D;
    --ink:#12184A; --muted:rgba(18,24,74,.66); --line:#e7dfce;
    --display:'Poppins',system-ui,-apple-system,'Segoe UI',sans-serif;
    --body:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;
  }
  *{box-sizing:border-box}
  body{margin:0;background:var(--cream);color:var(--ink);font-family:var(--body);line-height:1.5;-webkit-font-smoothing:antialiased}
  .wrap{max-width:1080px;margin:0 auto;padding:0 20px}
  header{border-bottom:2px solid var(--navy);background:var(--cream)}
  .hbar{display:flex;align-items:center;gap:10px;height:60px}
  .logo{display:flex;align-items:center;gap:9px;font-family:var(--display);font-weight:800;font-size:19px;letter-spacing:-.01em}
  .logo img{width:32px;height:32px;border-radius:50%}
  .hbadge{margin-left:auto;background:var(--navy);color:var(--cream);font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;padding:5px 11px;border-radius:999px}

  .hero{padding:44px 0 8px;text-align:center}
  .kicker{display:inline-block;background:#e7f6f2;color:#0b6d61;border:1.5px solid #bfe6dd;font-size:12px;font-weight:800;letter-spacing:.09em;text-transform:uppercase;padding:5px 12px;border-radius:999px}
  h1{font-family:var(--display);font-weight:900;font-size:clamp(30px,6vw,54px);line-height:1.06;letter-spacing:-.02em;margin:16px 0 0}
  h1 em{font-style:normal;background:linear-gradient(180deg,transparent 62%,var(--yellow) 62%);padding:0 .12em}
  .sub{font-size:clamp(16px,2.1vw,19px);color:var(--muted);max-width:620px;margin:14px auto 0}
  .cta{display:inline-block;margin-top:22px;background:var(--navy);color:var(--cream);font-family:var(--display);font-weight:800;font-size:17px;text-decoration:none;padding:15px 30px;border-radius:14px;box-shadow:5px 5px 0 var(--yellow);border:none;cursor:pointer}
  .cta:active{transform:translate(2px,2px);box-shadow:3px 3px 0 var(--yellow)}
  .cta-note{font-size:13.5px;color:var(--muted);margin-top:10px}

  h2{font-family:var(--display);font-weight:900;font-size:clamp(22px,3.6vw,32px);letter-spacing:-.015em;text-align:center;margin:0 0 6px}
  .h2sub{text-align:center;color:var(--muted);font-size:15.5px;margin:0 auto 24px;max-width:560px}
  section{padding:44px 0}
  .band{background:#fffdf8;border-top:2px solid var(--navy);border-bottom:2px solid var(--navy)}

  /* Showcase: live previews in scaled iframes. Real sites, clickable. */
  .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}
  .tile{background:#fff;border:2px solid var(--navy);border-radius:16px;overflow:hidden;box-shadow:5px 5px 0 var(--navy);text-decoration:none;color:inherit;display:block}
  /* display:block matters - these are spans (a valid child of <a>), and height
     is ignored on inline elements, which collapses the tile to a sliver. */
  .shot{display:block;position:relative;height:210px;overflow:hidden;background:#eee;border-bottom:2px solid var(--navy)}
  .shot iframe{position:absolute;top:0;left:0;width:1280px;height:900px;border:0;transform:scale(.276);transform-origin:top left;pointer-events:none}
  .tmeta{display:block;padding:11px 14px}
  .tname{display:block;font-family:var(--display);font-weight:800;font-size:15px}
  .ttrade{display:block;font-size:12.5px;color:var(--muted)}
  @media(max-width:820px){.grid{grid-template-columns:1fr}.shot{height:230px}.shot iframe{transform:scale(.42)}}

  .steps{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;counter-reset:s}
  .step{background:var(--cream);border:2px solid var(--navy);border-radius:16px;padding:20px}
  .step b{display:block;font-family:var(--display);font-size:16.5px;margin-bottom:5px}
  .step p{margin:0;font-size:14.5px;color:var(--muted)}
  .snum{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:var(--yellow);border:2px solid var(--navy);font-family:var(--display);font-weight:800;font-size:14px;margin-bottom:10px}
  @media(max-width:820px){.steps{grid-template-columns:1fr}}

  .offer{max-width:520px;margin:0 auto;background:var(--yellow);border:2.5px solid var(--navy);border-radius:20px;box-shadow:7px 7px 0 var(--navy);padding:26px;text-align:center}
  .price{font-family:var(--display);font-weight:900;font-size:clamp(32px,6vw,46px);line-height:1.05;letter-spacing:-.02em}
  .pnote{font-size:15px;font-weight:600;margin-top:4px}
  .incl{list-style:none;margin:18px 0 0;padding:0;text-align:left;display:grid;gap:8px}
  .incl li{display:flex;gap:9px;font-size:14.5px;align-items:flex-start}
  .ck{flex:none;font-weight:900}

  .guar{display:flex;gap:11px;align-items:flex-start;background:#eaf7f1;border:1.5px solid #bfe6d4;border-radius:13px;padding:13px 15px;margin:20px auto 0;max-width:520px;color:#12603f;font-size:14px}
  .guar img{flex:none;width:46px;height:46px;border-radius:50%;object-fit:cover;border:2px solid #12603f}
  .guar .by{display:block;margin-top:3px;font-weight:800;font-size:12px}

  /* Brief form */
  .formwrap{max-width:520px;margin:0 auto;background:#fffdf8;border:2px solid var(--navy);border-radius:18px;padding:22px;box-shadow:5px 5px 0 var(--navy)}
  label{display:block;font-weight:700;font-size:14px;margin:14px 0 5px}
  label:first-of-type{margin-top:0}
  input,textarea{width:100%;font:inherit;font-size:15px;padding:11px 13px;border:2px solid var(--line);border-radius:11px;background:#fff;color:var(--ink)}
  input:focus,textarea:focus{outline:none;border-color:var(--teal)}
  .req{color:#b00;font-weight:800}
  .err{color:#b00;font-size:13.5px;margin-top:10px;min-height:18px}
  .ok{display:none;text-align:center;padding:8px 0}
  .ok h3{font-family:var(--display);font-size:22px;margin:0 0 6px}
  .ok p{color:var(--muted);margin:0}
  footer{border-top:2px solid var(--navy);padding:22px 0;text-align:center;font-size:13px;color:var(--muted)}
</style>
</head>
<body data-variant="<?= htmlspecialchars($V['key'], ENT_QUOTES) ?>">

<header>
  <div class="wrap hbar">
    <span class="logo"><img src="/preview/wizzy-wave.gif" alt="">WebWiz</span>
    <span class="hbadge"><?= $V['badge'] ?></span>
  </div>
</header>

<section class="hero">
  <div class="wrap">
    <span class="kicker"><?= $V['kicker'] ?></span>
    <h1><?= $V['headline'] ?></h1>
    <p class="sub"><?= $V['sub'] ?></p>
    <?php if (!empty($V['builder'])): ?>
      <a class="cta" href="/o/<?= htmlspecialchars($V['key'], ENT_QUOTES) ?>/try/" data-builder>&#9755; <?= htmlspecialchars($V['cta'], ENT_QUOTES) ?></a>
      <p class="cta-note">Free to watch it build. No card needed.</p>
    <?php else: ?>
      <button class="cta" type="button" data-jump>&#9755; <?= htmlspecialchars($V['cta'], ENT_QUOTES) ?></button>
      <p class="cta-note">Takes about a minute. No card needed to start.</p>
    <?php endif; ?>
  </div>
</section>

<section class="band">
  <div class="wrap">
    <h2>Real sites we've built</h2>
    <p class="h2sub">Not mockups. These are live pages we made for local businesses. Tap any of them to look around.</p>
    <div class="grid">
      <?php foreach ($SHOWCASE as $s): ?>
      <a class="tile" href="/preview/<?= htmlspecialchars($s['token'], ENT_QUOTES) ?>/v1/index.html" target="_blank" rel="noopener">
        <span class="shot">
          <iframe src="/preview/<?= htmlspecialchars($s['token'], ENT_QUOTES) ?>/v1/index.html"
                  loading="lazy" tabindex="-1" scrolling="no" title="<?= htmlspecialchars($s['name'], ENT_QUOTES) ?>"></iframe>
        </span>
        <span class="tmeta">
          <span class="tname"><?= htmlspecialchars($s['name']) ?></span><br>
          <span class="ttrade"><?= htmlspecialchars($s['trade']) ?></span>
        </span>
      </a>
      <?php endforeach; ?>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <h2>How it works</h2>
    <p class="h2sub">You do about a minute of work. We do the rest.</p>
    <div class="steps">
      <div class="step"><span class="snum">1</span><b>Tell us about your business</b><p>Your name, what you do, and anything you want on the site. A couple of sentences is plenty.</p></div>
      <div class="step"><span class="snum">2</span><b>A designer builds it</b><p>A real person on our team designs your site, usually within 3 business days. No templates.</p></div>
      <div class="step"><span class="snum">3</span><b>You approve it</b><p>We revise until you love it. It only goes live when you say so.</p></div>
    </div>
  </div>
</section>

<section class="band">
  <div class="wrap">
    <h2>What it costs</h2>
    <p class="h2sub">No setup fees, no contracts, no surprises.</p>
    <div class="offer">
      <div class="price"><?= $V['price_line'] ?></div>
      <div class="pnote"><?= $V['price_note'] ?></div>
      <ul class="incl">
        <li><span class="ck">&#10003;</span><span>Designed by a real person, not a template</span></li>
        <li><span class="ck">&#10003;</span><span>Hosting, SSL and daily backups included</span></li>
        <li><span class="ck">&#10003;</span><span>Revisions until you love it, no round limit</span></li>
        <li><span class="ck">&#10003;</span><span>Cancel anytime. No contract, no cancellation fee</span></li>
        <li><span class="ck">&#10003;</span><span>Your $50/month price is locked and never goes up</span></li>
      </ul>
    </div>
    <div class="guar">
      <?php
        $lp = '';
        foreach (['laura.jpg','laura.jpeg','laura.webp','laura.png'] as $lf) {
            if (is_file(dirname(__DIR__) . '/preview/' . $lf)) { $lp = '/preview/' . $lf; break; }
        }
        if ($lp !== ''): ?>
        <img src="<?= htmlspecialchars($lp, ENT_QUOTES) ?>" alt="Laura Montoya, Co-founder at WebWiz" width="46" height="46" loading="lazy">
      <?php endif; ?>
      <span><strong>100% satisfaction guarantee.</strong> &ldquo;We revise until you love it, however many rounds it takes.&rdquo;
        <span class="by">Laura Montoya, Co-founder</span></span>
    </div>
  </div>
</section>

<?php if (!empty($V['builder'])): ?>
<section id="brief">
  <div class="wrap" style="text-align:center">
    <h2>Ready to see yours?</h2>
    <p class="h2sub">Type your business name and watch the builder work. Takes about two minutes and costs nothing.</p>
    <a class="cta" href="/o/<?= htmlspecialchars($V['key'], ENT_QUOTES) ?>/try/" data-builder>&#9755; <?= htmlspecialchars($V['cta'], ENT_QUOTES) ?></a>
  </div>
</section>
<?php else: ?>
<section id="brief">
  <div class="wrap">
    <h2>Tell us what you want</h2>
    <p class="h2sub">We'll email you when your site is ready to look at.</p>
    <div class="formwrap">
      <form id="offerForm" novalidate>
        <div id="formFields">
          <label for="biz">Your business name <span class="req">*</span></label>
          <input id="biz" name="business" autocomplete="organization" placeholder="e.g. 1 Down Fence Company">

          <label for="what">What does your business do? <span class="req">*</span></label>
          <textarea id="what" name="about" rows="3" placeholder="Fencing installation for homes and farms around Enterprise, Alabama."></textarea>

          <label for="want">Anything you want on the site? <span style="font-weight:500;color:var(--muted)">(optional)</span></label>
          <textarea id="want" name="wants" rows="2" placeholder="Photos of our work, a quote form, our phone number up top..."></textarea>

          <label for="email">Where should we send it? <span class="req">*</span></label>
          <input id="email" name="contact" inputmode="email" autocomplete="email" placeholder="you@yourbusiness.com or a phone number">

          <p class="err" id="err"></p>
          <button class="cta" type="submit" id="go" style="width:100%;margin-top:4px"><?= htmlspecialchars($V['cta'], ENT_QUOTES) ?></button>
        </div>
        <div class="ok" id="ok">
          <h3>Got it &mdash; thank you.</h3>
          <p>A designer will start on your site and email you when there's something to look at, usually within 3 business days.</p>
        </div>
      </form>
    </div>
  </div>
</section>
<?php endif; ?>

<footer>
  <div class="wrap">Built by humans (and one spider) who care about your site. &copy; <?= date('Y') ?> WebWiz</div>
</footer>

<script>
(function(){
  var VARIANT = document.body.getAttribute('data-variant');
  document.querySelectorAll('[data-jump]').forEach(function(b){
    b.addEventListener('click', function(){
      document.getElementById('brief').scrollIntoView({behavior:'smooth', block:'start'});
      setTimeout(function(){ var el=document.getElementById('biz'); if(el) el.focus(); }, 450);
    });
  });

  // Tell Meta which cell this view belongs to, so the pixel data can be split
  // by price the same way our own try_events are.
  try { if (window.wwMetaTrack) window.wwMetaTrack('ViewContent', {content_name:'offer_'+VARIANT, content_category:'price_test'}); } catch(e){}

  document.querySelectorAll('[data-builder]').forEach(function(a){
    a.addEventListener('click', function(){
      try { if (window.wwMetaTrack) window.wwMetaTrack('InitiateCheckout', {content_name:'offer_'+VARIANT+'_builder'}); } catch(e){}
    });
  });

  var form = document.getElementById('offerForm');
  var err  = document.getElementById('err');
  var go   = document.getElementById('go');
  // The builder variant has no brief form - nothing below applies to it.
  if (!form) { return; }

  form.addEventListener('submit', function(e){
    e.preventDefault();
    err.textContent = '';
    var biz     = document.getElementById('biz').value.trim();
    var about   = document.getElementById('what').value.trim();
    var wants   = document.getElementById('want').value.trim();
    var contact = document.getElementById('email').value.trim();

    if (!biz)                 { err.textContent = 'Please tell us your business name.'; return; }
    if (about.length < 8)     { err.textContent = 'A sentence about what you do, please.'; return; }
    if (contact.length < 6)   { err.textContent = 'We need an email or phone number to send it to.'; return; }

    go.disabled = true; go.textContent = 'Sending...';
    fetch('/api/offer_lead.php', {
      method:'POST', headers:{'Content-Type':'application/json'},
      body: JSON.stringify({variant:VARIANT, business:biz, about:about, wants:wants, contact:contact})
    }).then(function(r){ return r.json().catch(function(){ return {ok:false}; }); })
      .then(function(j){
        if (j && j.ok) {
          // Lead is saved first and separately. If Stripe then fails or the
          // visitor abandons checkout we still have the lead and can follow up,
          // which is the whole point of paying for the click.
          try { if (window.wwMetaTrack) window.wwMetaTrack('Lead', {content_name:'offer_'+VARIANT, content_category:'price_test'}); } catch(e){}
          go.textContent = 'Taking you to checkout...';
          fetch('/api/offer_checkout.php', {
            method:'POST', headers:{'Content-Type':'application/json'},
            body: JSON.stringify({variant:VARIANT, lead_id:j.id, email:contact})
          }).then(function(r){ return r.json().catch(function(){ return {ok:false}; }); })
            .then(function(c){
              if (c && c.ok && c.url) {
                try { if (window.wwMetaTrack) window.wwMetaTrack('InitiateCheckout', {content_name:'offer_'+VARIANT}); } catch(e){}
                window.location.href = c.url;
              } else {
                // Checkout unavailable: show the thank-you rather than a dead end.
                // The brief is already captured, so a human can still pick it up.
                document.getElementById('formFields').style.display = 'none';
                document.getElementById('ok').style.display = 'block';
              }
            })
            .catch(function(){
              document.getElementById('formFields').style.display = 'none';
              document.getElementById('ok').style.display = 'block';
            });
          return;
        }
        if (false) {
          document.getElementById('formFields').style.display = 'none';
          document.getElementById('ok').style.display = 'block';
          // wwMetaTrack fires the pixel AND the server-side CAPI copy with a
          // shared eventID, so Meta deduplicates them. A bare fbq('track')
          // would have been browser-only and lost to iOS/ad blockers.
          try { if (window.wwMetaTrack) window.wwMetaTrack('Lead', {content_name:'offer_'+VARIANT, content_category:'price_test'}); } catch(e){}
        } else {
          err.textContent = (j && j.error) ? j.error : 'Something went wrong. Please try again.';
          go.disabled = false; go.textContent = <?= json_encode($V['cta']) ?>;
        }
      })
      .catch(function(){
        err.textContent = 'Network problem. Please try again.';
        go.disabled = false; go.textContent = <?= json_encode($V['cta']) ?>;
      });
  });
})();
</script>
</body>
</html>
