<?php
/**
 * /o/_offer.php - shared template for the price-test landing pages.
 *
 * WHY THIS EXISTS
 * Meta ad comments push back hard on price ("How you charging $500 for a website
 * in 2026", "Lovable is $20"). These pages test a lower entry price, on two
 * axes at once:
 *   a vs b  = PRICE    ($100 build vs free build)      both WITH the builder
 *   b vs c  = BUILDER  (AI builder vs showcase only)   both free build
 *
 * Cells A and B DO run the AI generator: their CTA goes to /o/<v>/try/, which is
 * the real /try builder wrapped to carry the offer. (These pages originally
 * avoided the generator on purpose; that changed on 2026-08-01, and only cell C
 * still works the old way.) Cell C shows sites we have already built, takes a
 * brief, and a human designs it - which is why cell C is the only cell whose
 * visitors reach checkout with no job token.
 *
 * These pages are UNLISTED: noindex, disallowed in robots.txt, linked from
 * nowhere. Only people arriving from the ad should ever see them.
 *
 * Each variant is a thin wrapper in /o/<slug>/index.php that sets $WW_VARIANT
 * and includes this file. Add a variant by adding a row to $VARIANTS plus a
 * two-line wrapper directory.
 */
declare(strict_types=1);

if (!isset($WW_VARIANT)) { header('Location: /'); exit; }

require_once '/var/www/sites/trywebwiz/private/webwiz_lib.php';

// Keep these pages out of search results. The meta tag below does the same job,
// but this header is belt-and-braces AND cannot be undone by anything else:
// robots.txt is regenerated by the SeedSite SEO manager ("# Managed by SeedSite
// SEO"), which silently reverted a Disallow: /o/ line added on 2026-08-01. Do
// not rely on robots.txt to hide these pages.
header('X-Robots-Tag: noindex, nofollow, noarchive');

// FIX (2026-08-03): these are MEASURED landing pages behind live paid traffic.
// The site-wide `Cache-Control: public, max-age=86400` in public/.htaccess plus
// LiteSpeed's `CacheEnable public /` meant a shared cache could hand cell A's
// HTML to a cell B visitor, and could serve the ?success=1 receipt page to a
// stranger. Per-variant tracking, the post-checkout receipt and the Stripe
// session id are all per-visit, so nothing here is publicly cacheable.
header('Cache-Control: no-store, no-cache, must-revalidate, private, max-age=0');
header('Pragma: no-cache');
header('Expires: 0');

// ---------------------------------------------------------------------------
// Variant definitions. price_cents is the one-time build fee.
// ---------------------------------------------------------------------------
// Two axes, three cells:
//   a vs b  = PRICE    ($100 build  vs  free build)      both WITH the builder
//   b vs c  = BUILDER  (AI builder  vs  showcase only)   both free build
// Only A ever charges a build fee. B and C bill the $50/month and nothing else.
// 'builder' => true sends the visitor into the /try generator instead of
// showing the brief form.
// Cells B and C bill the first $50 at checkout (trial => 0), while the page
// sells the WEBSITE as free. Both are true, and the second has to be said at the
// point of payment or the charge reads as a surprise - which is how chargebacks
// start. A is unaffected: its page already leads with "$100 to build".
$PAY_NOTE = 'The website is free. <strong>Getting started is $50</strong> &mdash; it covers your '
          . 'hosting and setup, then it&rsquo;s $50/month. Cancel anytime.';

$VARIANTS = [
    // A: $100 one-time build, WITH the builder.
    'a' => [
        'key'        => 'a',
        'builder'    => true,
        'price_cents'=> 10000,   // $100 one-time build fee
        'monthly'    => 5000,    // $50/month hosting
        'kicker'     => 'For local businesses',
        'headline'   => 'Watch your website <em>build itself</em>.',
        'sub'        => 'Type your business name and watch a real website appear in about two minutes. If you like it, it is $100 to launch, then $50/month to host and look after it.',
        'price_line' => '$100 to build',
        'price_note' => 'then $50/month for hosting &amp; care',
        'cta'        => 'Build my site now',
        'badge'      => 'Flat $100',
    ],
    // B: free build, WITH the builder. Same experience as A, no build fee -
    // that pairing is what makes a vs b a clean price test.
    'b' => [
        'key'        => 'b',
        'builder'    => true,
        'price_cents'=> 0,       // no build fee - $50/month is the whole cost
        'monthly'    => 5000,
        'kicker'     => 'For local businesses',
        'headline'   => 'Watch your website <em>build itself</em>. Free.',
        'sub'        => 'Type your business name and watch a real website appear in about two minutes. Building it costs nothing. You pay $50/month to host it, and that is the whole cost of having a website.',
        'price_line' => '$50/month',
        'price_note' => 'no build fee &mdash; the website itself is free',
        'cta'        => 'Build my site free',
        'badge'      => 'Website built free',
        // trial => 0 in offer_checkout.php, so the first $50 is charged the
        // moment they check out. Say so next to the button, every time.
        'pay_note'   => $PAY_NOTE,
    ],
    // C: free build, NO builder. Showcase only, $50 today opens the account.
    'c' => [
        'key'        => 'c',
        'builder'    => false,
        'price_cents'=> 0,       // no build fee - the $50 IS month one
        'monthly'    => 5000,
        'kicker'     => 'For local businesses',
        'headline'   => 'The website is <em>free</em>. You pay for hosting.',
        'sub'        => 'A real designer builds your site for nothing, usually within 3 business days. You pay $50/month to host it and look after it, and that is the whole cost of having a website.',
        'price_line' => '$50/month',
        'price_note' => 'no build fee &mdash; the website itself is free',
        'cta'        => 'Start my free website',
        'badge'      => 'Website built free',
        // Same as B: free build, but the $50 is taken at checkout, not later.
        'pay_note'   => $PAY_NOTE,
    ],
    // -----------------------------------------------------------------------
    // T: the guarded $1 LIVE-PAYMENT TEST cell. NOT an offer and never shown to
    // anyone - /o/t/index.php 404s without the secret in ?k=.
    //
    // It exists because the entire chain downstream of a real
    // checkout.session.completed (webhook fulfilment, offer_leads.status,
    // checkout_completed, the Purchase + Subscribe CAPI events, this receipt
    // block, the confirmation email) has never once executed against a genuinely
    // paid /o session. Proving it needs a real card, and a real card needs a
    // price we are willing to actually pay - hence $1 + $1/month.
    //
    // This cell is the TOKENLESS half of the test (brief form, no job token),
    // deliberately mirroring cell C, because webhook.php's tokenless branch is
    // the one that used to record nothing at all. /o/t/try/ is the token half.
    // 't' is a distinct key so every row, event and metric it produces is
    // filtered out of A/B/C reporting with `variant <> 't'`.
    // -----------------------------------------------------------------------
    't' => [
        'key'        => 't',
        'builder'    => false,
        'price_cents'=> 100,     // $1.00 one-time
        'monthly'    => 100,     // $1.00/month, no trial
        'kicker'     => 'Internal test page &mdash; not an offer',
        'headline'   => '$1 live-payment <em>test</em>.',
        'sub'        => 'This is an internal end-to-end payment test for the WebWiz team. It is not an offer, '
                      . 'it is not for sale, and nothing here will be built. It charges $1.00 today and $1.00 a month '
                      . 'so a real card can prove the payment chain works.',
        'price_line' => '$1.00 + $1.00/mo',
        'price_note' => 'internal test cell &mdash; tokenless (brief) path',
        'cta'        => 'Run the $1 test checkout',
        'badge'      => 'TEST CELL',
        'pay_note'   => 'Internal test. <strong>$1.00 is charged now</strong>, then $1.00/month until cancelled. '
                      . 'Cancel the subscription in Stripe as soon as the test is verified.',
    ],
];

$V = $VARIANTS[$WW_VARIANT] ?? $VARIANTS['a'];

// ---------------------------------------------------------------------------
// POST-CHECKOUT STATE (added 2026-08-03).
//
// offer_checkout.php sends tokenless (cell C) buyers back to
//   /o/c/?success=1&sid=cs_...   on success
//   /o/c/?cancelled=1            on cancel
// and until now this file ignored both. A buyer who had just been charged $50
// landed back on "The website is free... Start my free website" with the brief
// form open and no receipt, which reads as "the payment did not work" and is
// how refund requests and chargebacks start.
// ---------------------------------------------------------------------------
$ww_success   = (string)($_GET['success']   ?? '') === '1';
$ww_cancelled = (string)($_GET['cancelled'] ?? '') === '1';
$ww_sid = '';
if (preg_match('~^cs_[A-Za-z0-9_]{8,120}$~', (string)($_GET['sid'] ?? ''))) {
    $ww_sid = (string)$_GET['sid'];
}
// A success URL with no usable session id is not a receipt we can stand behind.
if ($ww_success && $ww_sid === '') { $ww_success = false; }
if ($ww_success) { $ww_cancelled = false; }

// Receipt facts. Ask Stripe for the truth; fall back to this cell's own price
// so the page still says something correct if the API call fails.
$ww_paid_cents    = null;
$ww_paid_status   = '';
$ww_receipt_email = '';
$ww_currency      = 'USD';
if ($ww_success) {
    try {
        $sec = function_exists('ww_secrets') ? ww_secrets() : [];
        $sk  = (string)($sec['STRIPE_SECRET_KEY'] ?? '');
        if ($sk !== '') {
            $ch = curl_init('https://api.stripe.com/v1/checkout/sessions/' . urlencode($ww_sid));
            curl_setopt_array($ch, [
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_USERPWD        => $sk . ':',
                CURLOPT_TIMEOUT        => 6,
                CURLOPT_CONNECTTIMEOUT => 4,
            ]);
            $r = curl_exec($ch);
            $hc = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);
            $sj = json_decode((string)$r, true);
            if ($hc === 200 && is_array($sj)) {
                if (isset($sj['amount_total']))   $ww_paid_cents    = (int)$sj['amount_total'];
                if (isset($sj['payment_status'])) $ww_paid_status   = (string)$sj['payment_status'];
                if (!empty($sj['currency']))      $ww_currency      = strtoupper((string)$sj['currency']);
                $ww_receipt_email = (string)($sj['customer_details']['email'] ?? ($sj['customer_email'] ?? ''));
            }
        }
    } catch (Throwable $e) { /* fall through to the static fallback below */ }
}
if ($ww_paid_cents === null) {
    $ww_paid_cents = ((int)$V['price_cents'] > 0) ? (int)$V['price_cents'] : (int)$V['monthly'];
}
// Short human reference for support, plus the full Stripe id for us.
$ww_ref = $ww_sid !== '' ? 'WW-' . strtoupper(substr($ww_sid, -10)) : '';

// Only claim money changed hands if Stripe says it did. Stripe normally only
// sends anyone to success_url after payment, but ?success=1&sid=... is just a
// URL and can be reached with a session that was never paid - telling that
// person "Paid today $50" would be a false receipt.
// If we could NOT reach Stripe at all ($ww_paid_status === '') we give the
// buyer the benefit of the doubt and show the receipt: an API timeout on our
// side must not tell a paying customer their payment failed.
$ww_confirmed = ($ww_paid_status === '' || in_array($ww_paid_status, ['paid', 'no_payment_required'], true));

// ---------------------------------------------------------------------------
// Showcase. ONLY sites that have been looked at by a human and judged
// presentable - a bad tile here costs more than an empty grid.
// ---------------------------------------------------------------------------
$SHOWCASE = [
    ['token' => 'd1fa58b89d4ce070c8700954', 'name' => '1 Down Fence Company', 'trade' => 'Fencing contractor'],
    ['token' => 'e2f229e6240312fb9b6a3c8c', 'name' => 'Beaver Roofing',        'trade' => 'Roofing'],
    ['token' => '96e77503e68e48db16f7e9cf', 'name' => 'Ridgeline Coffee',      'trade' => 'Coffee roaster'],
];

// Record the pageview so variants can be compared on more than clicks.
// NOT on the post-checkout receipt: that is the same person coming back from
// Stripe, and counting it as a fresh view inflates the denominator of the
// lead-per-view metric this whole price test exists to produce.
if ($ww_success) {
    try {
        ww_db()->prepare("INSERT INTO try_events (event, session_id, payload, ip, user_agent) VALUES ('offer_success_view', ?, ?, ?, ?)")
           ->execute([
               $ww_sid ?: null,
               json_encode(['variant' => $V['key'], 'amount_total' => $ww_paid_cents, 'payment_status' => $ww_paid_status], JSON_UNESCAPED_SLASHES),
               substr((string)($_SERVER['REMOTE_ADDR'] ?? ''), 0, 45),
               substr((string)($_SERVER['HTTP_USER_AGENT'] ?? ''), 0, 300),
           ]);
    } catch (Throwable $e) { /* never let analytics break the receipt */ }
    // Close the loop on the lead even if the Stripe webhook is late or fails.
    // Stripe's own payment_status is the authority, never the query string.
    if ($ww_paid_status === 'paid' || $ww_paid_status === 'no_payment_required') {
        try {
            $dbp = ww_db();
            ww_db_write_retry(function () use ($dbp, $ww_sid) {
                return $dbp->prepare("UPDATE offer_leads SET status='purchased' WHERE stripe_session_id = ? AND status <> 'purchased'")
                           ->execute([$ww_sid]);
            });
        } catch (Throwable $e) { /* webhook.php also does this */ }
    }
} else {
try {
    $db = ww_db();
    // try_events has no 'detail' column - the variant goes in payload, matching
    // how hero_view and the rest of the /try funnel events are recorded.
    $db->prepare("INSERT INTO try_events (event, payload, ip, user_agent) VALUES ('offer_view', ?, ?, ?)")
       ->execute([
           json_encode(['variant' => $V['key'], 'from' => $_SERVER['HTTP_REFERER'] ?? null], JSON_UNESCAPED_SLASHES),
           substr((string)($_SERVER['REMOTE_ADDR'] ?? ''), 0, 45),
           substr((string)($_SERVER['HTTP_USER_AGENT'] ?? ''), 0, 300),
       ]);
} catch (Throwable $e) { /* never let analytics break the page */ }
}

$ver = defined('WW_VERSION') ? WW_VERSION : '0';
$hh  = fn($x) => htmlspecialchars((string)$x, ENT_QUOTES);
$ww_money = fn(int $c) => '$' . number_format($c / 100, ($c % 100 === 0) ? 0 : 2);
?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Unlisted price test. Must never be indexed or linked publicly. -->
<meta name="robots" content="noindex, nofollow, noarchive">
<title>Websites for local businesses &middot; WebWiz</title>
<meta name="description" content="A real designer builds your website. See real examples and tell us what you want.">
<link rel="icon" href="/favicon.ico">
<?php
// Meta Pixel + CAPI, reusing the same bootstrap /try uses (pixel 1974530180093513).
// This gives us window.wwMetaTrack(), which fires the browser pixel AND posts to
// /api/capi.php with a shared eventID so the two are deduplicated. Rolling our
// own fbq() call here would have produced double-counted, unattributed events.
@require_once '/var/www/sites/trywebwiz/public/api/_meta.php';
if (function_exists('ww_meta_pixel_base_html')) { echo ww_meta_pixel_base_html(); }
?>
<script src="/api/sentry.js.php" defer></script>
<style>
  :root{
    --cream:#FAF5EA; --navy:#12184A; --teal:#12A594; --yellow:#FFC83D;
    --ink:#12184A; --muted:rgba(18,24,74,.66); --line:#e7dfce;
    --display:'Poppins',system-ui,-apple-system,'Segoe UI',sans-serif;
    --body:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;
  }
  *{box-sizing:border-box}
  body{margin:0;background:var(--cream);color:var(--ink);font-family:var(--body);line-height:1.5;-webkit-font-smoothing:antialiased}
  .wrap{max-width:1080px;margin:0 auto;padding:0 20px}
  header{border-bottom:2px solid var(--navy);background:var(--cream)}
  .hbar{display:flex;align-items:center;gap:10px;height:60px}
  .logo{display:flex;align-items:center;gap:9px;font-family:var(--display);font-weight:800;font-size:19px;letter-spacing:-.01em}
  .logo img{width:32px;height:32px;border-radius:50%}
  .hbadge{margin-left:auto;background:var(--navy);color:var(--cream);font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;padding:5px 11px;border-radius:999px}

  .hero{padding:44px 0 8px;text-align:center}
  .kicker{display:inline-block;background:#e7f6f2;color:#0b6d61;border:1.5px solid #bfe6dd;font-size:12px;font-weight:800;letter-spacing:.09em;text-transform:uppercase;padding:5px 12px;border-radius:999px}
  h1{font-family:var(--display);font-weight:900;font-size:clamp(30px,6vw,54px);line-height:1.06;letter-spacing:-.02em;margin:16px 0 0}
  h1 em{font-style:normal;background:linear-gradient(180deg,transparent 62%,var(--yellow) 62%);padding:0 .12em}
  .sub{font-size:clamp(16px,2.1vw,19px);color:var(--muted);max-width:620px;margin:14px auto 0}
  .cta{display:inline-block;margin-top:22px;background:var(--navy);color:var(--cream);font-family:var(--display);font-weight:800;font-size:17px;text-decoration:none;padding:15px 30px;border-radius:14px;box-shadow:5px 5px 0 var(--yellow);border:none;cursor:pointer}
  .cta:active{transform:translate(2px,2px);box-shadow:3px 3px 0 var(--yellow)}
  .cta-note{font-size:13.5px;color:var(--muted);margin-top:10px}
  /* Payment disclosure for the free-build cells. Deliberately darker and
     heavier than .cta-note - this is the line that has to be read, not skimmed
     past, because the $50 is taken at checkout and not a month later. */
  .cta-pay{font-size:14px;color:var(--ink);opacity:.92;margin:8px auto 0;max-width:460px;line-height:1.45}
  .cta-pay strong{font-weight:800;white-space:nowrap}

  h2{font-family:var(--display);font-weight:900;font-size:clamp(22px,3.6vw,32px);letter-spacing:-.015em;text-align:center;margin:0 0 6px}
  .h2sub{text-align:center;color:var(--muted);font-size:15.5px;margin:0 auto 24px;max-width:560px}
  section{padding:44px 0}
  .band{background:#fffdf8;border-top:2px solid var(--navy);border-bottom:2px solid var(--navy)}

  /* Showcase: live previews in scaled iframes. Real sites, clickable. */
  .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}
  .tile{background:#fff;border:2px solid var(--navy);border-radius:16px;overflow:hidden;box-shadow:5px 5px 0 var(--navy);text-decoration:none;color:inherit;display:block}
  /* display:block matters - these are spans (a valid child of <a>), and height
     is ignored on inline elements, which collapses the tile to a sliver. */
  .shot{display:block;position:relative;height:210px;overflow:hidden;background:#eee;border-bottom:2px solid var(--navy)}
  .shot iframe{position:absolute;top:0;left:0;width:1280px;height:900px;border:0;transform:scale(.276);transform-origin:top left;pointer-events:none}
  .tmeta{display:block;padding:11px 14px}
  .tname{display:block;font-family:var(--display);font-weight:800;font-size:15px}
  .ttrade{display:block;font-size:12.5px;color:var(--muted)}
  @media(max-width:820px){.grid{grid-template-columns:1fr}.shot{height:230px}.shot iframe{transform:scale(.42)}}

  .steps{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;counter-reset:s}
  .step{background:var(--cream);border:2px solid var(--navy);border-radius:16px;padding:20px}
  .step b{display:block;font-family:var(--display);font-size:16.5px;margin-bottom:5px}
  .step p{margin:0;font-size:14.5px;color:var(--muted)}
  .snum{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:var(--yellow);border:2px solid var(--navy);font-family:var(--display);font-weight:800;font-size:14px;margin-bottom:10px}
  @media(max-width:820px){.steps{grid-template-columns:1fr}}

  .offer{max-width:520px;margin:0 auto;background:var(--yellow);border:2.5px solid var(--navy);border-radius:20px;box-shadow:7px 7px 0 var(--navy);padding:26px;text-align:center}
  .price{font-family:var(--display);font-weight:900;font-size:clamp(32px,6vw,46px);line-height:1.05;letter-spacing:-.02em}
  .pnote{font-size:15px;font-weight:600;margin-top:4px}
  .incl{list-style:none;margin:18px 0 0;padding:0;text-align:left;display:grid;gap:8px}
  .incl li{display:flex;gap:9px;font-size:14.5px;align-items:flex-start}
  .ck{flex:none;font-weight:900}

  .guar{display:flex;gap:11px;align-items:flex-start;background:#eaf7f1;border:1.5px solid #bfe6d4;border-radius:13px;padding:13px 15px;margin:20px auto 0;max-width:520px;color:#12603f;font-size:14px}
  .guar img{flex:none;width:46px;height:46px;border-radius:50%;object-fit:cover;border:2px solid #12603f}
  .guar .by{display:block;margin-top:3px;font-weight:800;font-size:12px}

  /* Brief form */
  .formwrap{max-width:520px;margin:0 auto;background:#fffdf8;border:2px solid var(--navy);border-radius:18px;padding:22px;box-shadow:5px 5px 0 var(--navy)}
  label{display:block;font-weight:700;font-size:14px;margin:14px 0 5px}
  label:first-of-type{margin-top:0}
  input,textarea{width:100%;font:inherit;font-size:15px;padding:11px 13px;border:2px solid var(--line);border-radius:11px;background:#fff;color:var(--ink)}
  input:focus,textarea:focus{outline:none;border-color:var(--teal)}
  .req{color:#b00;font-weight:800}
  .err{color:#b00;font-size:13.5px;margin-top:10px;min-height:18px}
  /* Checkout failure must look like a failure. The old code hid the form and
     showed the thank-you panel when checkout errored, so a buyer who was never
     charged believed the purchase had gone through. */
  .err.on{display:block;border:2px solid #b00;background:#fff1f1;border-radius:11px;padding:11px 13px;font-size:14px;line-height:1.45;font-weight:600}
  .notice{max-width:520px;margin:0 auto 18px;border:2px solid var(--navy);background:#fff8e0;border-radius:13px;padding:13px 15px;font-size:14.5px;line-height:1.45}
  .notice b{font-weight:800}
  /* Post-checkout receipt */
  .rcpt{max-width:560px;margin:0 auto;background:#fffdf8;border:2.5px solid var(--navy);border-radius:20px;box-shadow:7px 7px 0 var(--navy);padding:24px}
  .rcpt h3{font-family:var(--display);font-weight:900;font-size:19px;margin:0 0 14px}
  .rline{display:flex;justify-content:space-between;gap:14px;padding:9px 0;border-bottom:1.5px dashed var(--line);font-size:15px}
  .rline:last-of-type{border-bottom:none}
  .rline b{font-weight:800;white-space:nowrap}
  .rbig{font-size:19px}
  .rref{margin:16px 0 0;font-size:13.5px;color:var(--muted);word-break:break-all}
  .rref code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px;background:#f2ecdd;border-radius:6px;padding:2px 6px;color:var(--ink)}
  .ok{display:none;text-align:center;padding:8px 0}
  .ok h3{font-family:var(--display);font-size:22px;margin:0 0 6px}
  .ok p{color:var(--muted);margin:0}
  footer{border-top:2px solid var(--navy);padding:22px 0;text-align:center;font-size:13px;color:var(--muted)}
</style>
</head>
<body data-variant="<?= htmlspecialchars($V['key'], ENT_QUOTES) ?>">

<header>
  <div class="wrap hbar">
    <span class="logo"><img src="/preview/wizzy-wave.gif" alt="">WebWiz</span>
    <span class="hbadge"><?= $V['badge'] ?></span>
  </div>
</header>

<?php if ($ww_success): ?>
<!-- ===================== POST-CHECKOUT RECEIPT =====================
     Reached only from Stripe's success_url. The sales page and the brief form
     are deliberately NOT rendered here: this person has already paid. -->
<section class="hero">
  <div class="wrap">
    <?php if ($ww_confirmed): ?>
    <span class="kicker">Payment received</span>
    <h1>You&rsquo;re <em>all set</em>.</h1>
    <p class="sub">Thank you &mdash; your account is open and your brief is with our design team.
      <?php if ($ww_receipt_email !== ''): ?>A receipt is on its way to <strong><?= $hh($ww_receipt_email) ?></strong>.<?php endif; ?></p>
    <?php else: ?>
    <span class="kicker">Confirming your payment</span>
    <h1>Almost <em>there</em>.</h1>
    <p class="sub">Your bank has not confirmed this payment to us yet. That is normal for some payment
      methods and usually clears within a few minutes. We&rsquo;ll email you the moment it does &mdash; you
      do not need to pay again, and you do not need to do anything else.</p>
    <?php endif; ?>
  </div>
</section>

<section class="band">
  <div class="wrap">
    <h2><?= $ww_confirmed ? 'What you paid' : 'What this costs' ?></h2>
    <p class="h2sub">No contract, no cancellation fee. You can cancel any time.</p>
    <div class="rcpt">
      <div class="rline rbig"><span><?= $ww_confirmed ? 'Paid today' : 'Due today (awaiting confirmation)' ?></span><b><?= $hh($ww_money($ww_paid_cents)) ?> <?= $hh($ww_currency) ?></b></div>
      <div class="rline"><span>Your website build</span><b><?= (int)$V['price_cents'] > 0 ? $hh($ww_money((int)$V['price_cents'])) : '$0 &mdash; free' ?></b></div>
      <div class="rline"><span>Hosting &amp; care from next month</span><b><?= $hh($ww_money((int)$V['monthly'])) ?>/month</b></div>
      <div class="rline"><span>Cancel anytime</span><b>Yes</b></div>
      <?php if ($ww_ref !== ''): ?>
      <p class="rref">Your reference: <code><?= $hh($ww_ref) ?></code><br>
        Quote it if you email us. <span style="opacity:.75">(Order id <?= $hh($ww_sid) ?>)</span></p>
      <?php endif; ?>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <h2>What happens next</h2>
    <p class="h2sub">You do nothing else for now &mdash; we come to you.</p>
    <div class="steps">
      <div class="step"><span class="snum">1</span><b>We&rsquo;ve got your brief</b><p>Everything you told us is already with our team. There is no other form to fill in.</p></div>
      <div class="step"><span class="snum">2</span><b>A real designer builds it</b><p>A person on our team designs your site, usually within 3 business days. We&rsquo;ll email you the moment there is something to look at.</p></div>
      <div class="step"><span class="snum">3</span><b>You approve it</b><p>We revise until you love it, however many rounds it takes. It only goes live when you say so.</p></div>
    </div>
    <p class="h2sub" style="margin-top:26px">Questions in the meantime? Email
      <a href="mailto:hello@trywebwiz.com?subject=<?= rawurlencode('My WebWiz order ' . $ww_ref) ?>" style="color:var(--ink);font-weight:700">hello@trywebwiz.com</a>
      <?php if ($ww_ref !== ''): ?>and quote <strong><?= $hh($ww_ref) ?></strong><?php endif; ?>.</p>
  </div>
</section>
<?php else: ?>

<section class="hero">
  <div class="wrap">
    <span class="kicker"><?= $V['kicker'] ?></span>
    <h1><?= $V['headline'] ?></h1>
    <p class="sub"><?= $V['sub'] ?></p>
    <?php if (!empty($V['builder'])): ?>
      <a class="cta" href="/o/<?= htmlspecialchars($V['key'], ENT_QUOTES) ?>/try/" data-builder>&#9755; <?= htmlspecialchars($V['cta'], ENT_QUOTES) ?></a>
      <p class="cta-note">Free to watch it build. No card needed.</p>
    <?php else: ?>
      <button class="cta" type="button" data-jump>&#9755; <?= htmlspecialchars($V['cta'], ENT_QUOTES) ?></button>
      <p class="cta-note">Takes about a minute. No card needed to start.</p>
    <?php endif; ?>
    <?php if (!empty($V['pay_note'])): ?><p class="cta-pay"><?= $V['pay_note'] ?></p><?php endif; ?>
  </div>
</section>

<section class="band">
  <div class="wrap">
    <h2>Real sites we've built</h2>
    <p class="h2sub">Not mockups. These are live pages we made for local businesses. Tap any of them to look around.</p>
    <div class="grid">
      <?php foreach ($SHOWCASE as $s): ?>
      <a class="tile" href="/preview/<?= htmlspecialchars($s['token'], ENT_QUOTES) ?>/v1/index.html" target="_blank" rel="noopener">
        <span class="shot">
          <iframe src="/preview/<?= htmlspecialchars($s['token'], ENT_QUOTES) ?>/v1/index.html"
                  loading="lazy" tabindex="-1" scrolling="no" title="<?= htmlspecialchars($s['name'], ENT_QUOTES) ?>"></iframe>
        </span>
        <span class="tmeta">
          <span class="tname"><?= htmlspecialchars($s['name']) ?></span><br>
          <span class="ttrade"><?= htmlspecialchars($s['trade']) ?></span>
        </span>
      </a>
      <?php endforeach; ?>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <h2>How it works</h2>
    <p class="h2sub">You do about a minute of work. We do the rest.</p>
    <div class="steps">
      <div class="step"><span class="snum">1</span><b>Tell us about your business</b><p>Your name, what you do, and anything you want on the site. A couple of sentences is plenty.</p></div>
      <div class="step"><span class="snum">2</span><b>A designer builds it</b><p>A real person on our team designs your site, usually within 3 business days. No templates.</p></div>
      <div class="step"><span class="snum">3</span><b>You approve it</b><p>We revise until you love it. It only goes live when you say so.</p></div>
    </div>
  </div>
</section>

<section class="band">
  <div class="wrap">
    <h2>What it costs</h2>
    <p class="h2sub">No setup fees, no contracts, no surprises.</p>
    <div class="offer">
      <div class="price"><?= $V['price_line'] ?></div>
      <div class="pnote"><?= $V['price_note'] ?></div>
      <ul class="incl">
        <li><span class="ck">&#10003;</span><span>Designed by a real person, not a template</span></li>
        <li><span class="ck">&#10003;</span><span>Hosting, SSL and daily backups included</span></li>
        <li><span class="ck">&#10003;</span><span>Revisions until you love it, no round limit</span></li>
        <li><span class="ck">&#10003;</span><span>Cancel anytime. No contract, no cancellation fee</span></li>
        <li><span class="ck">&#10003;</span><span>Your $50/month price is locked and never goes up</span></li>
      </ul>
    </div>
    <div class="guar">
      <?php
        $lp = '';
        foreach (['laura.jpg','laura.jpeg','laura.webp','laura.png'] as $lf) {
            if (is_file(dirname(__DIR__) . '/preview/' . $lf)) { $lp = '/preview/' . $lf; break; }
        }
        if ($lp !== ''): ?>
        <img src="<?= htmlspecialchars($lp, ENT_QUOTES) ?>" alt="Laura Montoya, Co-founder at WebWiz" width="46" height="46" loading="lazy">
      <?php endif; ?>
      <span><strong>100% satisfaction guarantee.</strong> &ldquo;We revise until you love it, however many rounds it takes.&rdquo;
        <span class="by">Laura Montoya, Co-founder</span></span>
    </div>
  </div>
</section>

<?php if (!empty($V['builder'])): ?>
<section id="brief">
  <div class="wrap" style="text-align:center">
    <h2>Ready to see yours?</h2>
    <p class="h2sub">Type your business name and watch the builder work. Takes about two minutes and costs nothing.</p>
    <a class="cta" href="/o/<?= htmlspecialchars($V['key'], ENT_QUOTES) ?>/try/" data-builder>&#9755; <?= htmlspecialchars($V['cta'], ENT_QUOTES) ?></a>
    <?php if (!empty($V['pay_note'])): ?><p class="cta-pay"><?= $V['pay_note'] ?></p><?php endif; ?>
  </div>
</section>
<?php else: ?>
<section id="brief">
  <div class="wrap">
    <h2>Tell us what you want</h2>
    <p class="h2sub">We'll email you when your site is ready to look at.</p>
    <?php if ($ww_cancelled): ?>
    <!-- Back from an abandoned Stripe session. Say plainly that no money moved;
         a silent reset reads as "something broke" or "did I just get charged?" -->
    <div class="notice" id="cancelNote" role="status">
      <b>No charge was made.</b> You closed the payment page before anything was taken, so nothing has left your account.
      Your details are safe with us &mdash; fill the form in again below whenever you&rsquo;re ready, or just leave it and we&rsquo;ll email you.
    </div>
    <?php endif; ?>
    <div class="formwrap">
      <form id="offerForm" novalidate>
        <div id="formFields">
          <label for="biz">Your business name <span class="req">*</span></label>
          <input id="biz" name="business" autocomplete="organization" placeholder="e.g. 1 Down Fence Company">

          <label for="what">What does your business do? <span class="req">*</span></label>
          <textarea id="what" name="about" rows="3" placeholder="Fencing installation for homes and farms around Enterprise, Alabama."></textarea>

          <label for="want">Anything you want on the site? <span style="font-weight:500;color:var(--muted)">(optional)</span></label>
          <textarea id="want" name="wants" rows="2" placeholder="Photos of our work, a quote form, our phone number up top..."></textarea>

          <label for="email">Where should we send it? <span class="req">*</span></label>
          <input id="email" name="contact" inputmode="email" autocomplete="email" placeholder="you@yourbusiness.com or a phone number">

          <p class="err" id="err"></p>
          <button class="cta" type="submit" id="go" style="width:100%;margin-top:4px"><?= htmlspecialchars($V['cta'], ENT_QUOTES) ?></button>
          <?php if (!empty($V['pay_note'])): ?><p class="cta-pay" style="text-align:center"><?= $V['pay_note'] ?></p><?php endif; ?>
        </div>
        <div class="ok" id="ok">
          <h3>Got it &mdash; thank you.</h3>
          <p>A designer will start on your site and email you when there's something to look at, usually within 3 business days.</p>
        </div>
      </form>
    </div>
  </div>
</section>
<?php endif; ?>
<?php endif; /* $ww_success */ ?>

<footer>
  <div class="wrap">Built by humans (and one spider) who care about your site. &copy; <?= date('Y') ?> WebWiz</div>
</footer>

<script>
(function(){
  var VARIANT = document.body.getAttribute('data-variant');
  // Amount due TODAY for this cell (A=100, B=50, C=50). Every Meta event below
  // carries it, so per-cell value is comparable in Events Manager.
  var CELL_VALUE = <?= json_encode(round(((int)$V['price_cents'] > 0 ? (int)$V['price_cents'] : (int)$V['monthly']) / 100, 2)) ?>;
  var POST_CHECKOUT = <?= $ww_success ? 'true' : 'false' ?>;
  // Only the guarded $1 test cell carries a key. Every other cell sends '' and
  // offer_checkout.php then treats a tokenless request as cell C exactly as
  // before - this cannot re-price a live cell.
  var WW_TEST_KEY = <?= json_encode(($V['key'] === 't' && function_exists('ww_offer_test_key')) ? ww_offer_test_key() : '') ?>;

  if (POST_CHECKOUT) {
    // Purchase, fired with the SAME deterministic event_id webhook.php derives
    // from the Stripe session, so the browser Pixel and the server CAPI copy
    // dedupe into one conversion instead of counting the sale twice.
    try {
      // Only on a payment Stripe has actually confirmed - reporting a Purchase
      // for an unpaid session would poison the ad algorithm with fake buyers.
      var PEID = <?= json_encode(($ww_confirmed && $ww_paid_status !== '' && $ww_sid !== '') ? 'ww_' . substr(hash('sha256', $ww_sid), 0, 24) : '') ?>;
      var PVAL = <?= json_encode(round($ww_paid_cents / 100, 2)) ?>;
      if (PEID && window.fbq) {
        fbq('track', 'Purchase',
            {value: PVAL, currency: <?= json_encode($ww_currency) ?>,
             content_name: 'offer_' + VARIANT, content_category: 'price_test'},
            {eventID: PEID});
      }
    } catch(e){}
    return; // no ViewContent, no form wiring: this is a receipt, not a sales page.
  }

  if (document.getElementById('cancelNote')) {
    try { document.getElementById('brief').scrollIntoView({behavior:'smooth', block:'start'}); } catch(e){}
  }

  document.querySelectorAll('[data-jump]').forEach(function(b){
    b.addEventListener('click', function(){
      document.getElementById('brief').scrollIntoView({behavior:'smooth', block:'start'});
      setTimeout(function(){ var el=document.getElementById('biz'); if(el) el.focus(); }, 450);
    });
  });

  // Tell Meta which cell this view belongs to, so the pixel data can be split
  // by price the same way our own try_events are.
  try { if (window.wwMetaTrack) window.wwMetaTrack('ViewContent', {content_name:'offer_'+VARIANT, content_category:'price_test', value:CELL_VALUE, currency:'USD'}); } catch(e){}

  document.querySelectorAll('[data-builder]').forEach(function(a){
    a.addEventListener('click', function(){
      try { if (window.wwMetaTrack) window.wwMetaTrack('InitiateCheckout', {content_name:'offer_'+VARIANT+'_builder', content_category:'price_test', value:CELL_VALUE, currency:'USD'}); } catch(e){}
    });
  });

  var form = document.getElementById('offerForm');
  var err  = document.getElementById('err');
  var go   = document.getElementById('go');
  // The builder variant has no brief form - nothing below applies to it.
  if (!form) { return; }

  var CTA_LABEL = <?= json_encode($V['cta']) ?>;
  // The lead is saved before checkout is attempted. Remember its id so a retry
  // after a checkout failure does not write the same person in twice.
  var savedLeadId = 0;

  // A failed checkout must LOOK failed. Previously this hid the form and showed
  // "Got it - thank you.", so someone who had NOT been charged and had NOT
  // bought anything was told they were done.
  function checkoutFailed(msg){
    err.textContent = msg || 'We could not open the secure checkout just then. Nothing has been charged. Your details are saved \u2014 please try again.';
    err.classList.add('on');
    go.disabled = false;
    go.textContent = 'Try again \u2014 ' + CTA_LABEL;
    try { err.scrollIntoView({behavior:'smooth', block:'center'}); } catch(e){}
  }

  form.addEventListener('submit', function(e){
    e.preventDefault();
    err.textContent = '';
    var biz     = document.getElementById('biz').value.trim();
    var about   = document.getElementById('what').value.trim();
    var wants   = document.getElementById('want').value.trim();
    var contact = document.getElementById('email').value.trim();

    if (!biz)                 { err.textContent = 'Please tell us your business name.'; return; }
    if (about.length < 8)     { err.textContent = 'A sentence about what you do, please.'; return; }
    if (contact.length < 6)   { err.textContent = 'We need an email or phone number to send it to.'; return; }

    go.disabled = true; go.textContent = 'Sending...';
    err.classList.remove('on');

    // Retry path: the lead already exists, go straight back to checkout.
    if (savedLeadId) { startCheckout(savedLeadId, contact); return; }

    fetch('/api/offer_lead.php', {
      method:'POST', headers:{'Content-Type':'application/json'},
      body: JSON.stringify({variant:VARIANT, business:biz, about:about, wants:wants, contact:contact})
    }).then(function(r){ return r.json().catch(function(){ return {ok:false}; }); })
      .then(function(j){
        if (j && j.ok) {
          // Lead is saved first and separately. If Stripe then fails or the
          // visitor abandons checkout we still have the lead and can follow up,
          // which is the whole point of paying for the click.
          // wwMetaTrack fires the pixel AND the server-side CAPI copy with a
          // shared eventID, so Meta deduplicates them. A bare fbq('track')
          // would have been browser-only and lost to iOS/ad blockers.
          savedLeadId = j.id || 0;
          try { if (window.wwMetaTrack) window.wwMetaTrack('Lead', {content_name:'offer_'+VARIANT, content_category:'price_test', value:CELL_VALUE, currency:'USD'}); } catch(e){}
          startCheckout(savedLeadId, contact);
          return;
        }
        err.textContent = (j && j.error) ? j.error : 'Something went wrong. Please try again.';
        err.classList.add('on');
        go.disabled = false; go.textContent = CTA_LABEL;
      })
      .catch(function(){
        err.textContent = 'Network problem. Please try again.';
        err.classList.add('on');
        go.disabled = false; go.textContent = CTA_LABEL;
      });
  });

  function startCheckout(leadId, contact){
    go.disabled = true; go.textContent = 'Taking you to checkout...';
    fetch('/api/offer_checkout.php', {
      method:'POST', headers:{'Content-Type':'application/json'},
      body: JSON.stringify({lead_id:leadId, email:contact, test_key:WW_TEST_KEY})
    }).then(function(r){ return r.json().catch(function(){ return {ok:false}; }); })
      .then(function(c){
        if (c && c.ok && c.url) {
          try { if (window.wwMetaTrack) window.wwMetaTrack('InitiateCheckout', {content_name:'offer_'+VARIANT, content_category:'price_test', value:CELL_VALUE, currency:'USD'}); } catch(e){}
          window.location.href = c.url;
          return;
        }
        checkoutFailed(c && c.error);
      })
      .catch(function(){ checkoutFailed(null); });
  }
})();
</script>
</body>
</html>
