<?php
// 30 seeded industries used as defaults. Edit via /admin/?tab=templates.
// Each entry: slug, name, voice, hero, sections (allowed/preferred), ctas, images, banned, keywords (for auto-detect), prompt_block (the full chunk we paste into Sonnet's system prompt).
// Hit directly returns empty array (no output, no leak).
if (!defined('WW_ADMIN_LOAD') && php_sapi_name() !== 'cli') { http_response_code(403); exit; }

return [
[
  'slug' => 'restaurant', 'name' => 'Restaurant (sit-down)',
  'voice' => 'Warm, inviting, sensory. Use specific food language. No corporate-speak.',
  'hero'  => 'Big landscape food photo OR full-bleed dining room. Headline names a signature dish or the restaurant\'s soul — never "Welcome".',
  'sections' => 'menu teaser (3-6 highlight dishes with one-line descriptions), about/story (chef or owner photo + short story), location + hours + phone, photo gallery, reservations CTA',
  'banned' => 'pricing tables, FAQ, services grid, trust strip with logos',
  'ctas' => 'Reserve a table; View menu; Order online',
  'images' => 'food photos in a magazine grid; tight warm portraits of chef/owners; never stock food that doesn\'t match the cuisine',
  'keywords' => 'restaurant,menu,dine,dining,chef,kitchen,bistro,trattoria,reservation,prix fixe',
],
[
  'slug' => 'fast_casual', 'name' => 'Fast Casual / Takeout',
  'voice' => 'Punchy, friendly, energetic. Talk about the food itself — bold, fresh, made-fast. Local touchpoints (years, neighborhoods, ownership).',
  'hero'  => 'Action shot of food being made, OR a hero dish in macro. Bold headline like "We Love Tacos. Full Stop." — short, declarative, ownable.',
  'sections' => 'menu highlights (cards with photos + price), order online block, locations grid with hours, our story (brief), Instagram-style gallery, careers/franchise (if applicable)',
  'banned' => 'long-form about pages, white papers, FAQ, blog grid',
  'ctas' => 'Order now; Find a location; See the menu',
  'images' => 'close-up food, team in uniform, branded packaging, queue lines, real customer faces',
  'keywords' => 'taco,burger,pizza,burrito,sandwich,grill,fast,takeout,fast casual,quick service',
],
[
  'slug' => 'bakery', 'name' => 'Bakery / Patisserie',
  'voice' => 'Crafted, homey, a little romantic. Process language — "stone-milled", "long-fermented", "morning bake".',
  'hero'  => 'Hero shot of bread/pastry close-up at golden hour, or hands kneading dough. Headline references the craft, not the brand.',
  'sections' => 'daily menu / today\'s bakes, custom cake or wholesale ordering form, the baker (single portrait, story), shop hours + address, gallery of pastries',
  'banned' => 'corporate stat strip, "innovation"-speak',
  'ctas' => 'Order a custom cake; See today\'s bakes; Visit the shop',
  'images' => 'close-up textures (crumb, glaze, sprinkles), the oven, the baker, the shop interior at golden hour',
  'keywords' => 'bakery,pastry,bread,baguette,cake,croissant,patisserie,donut,muffin',
],
[
  'slug' => 'coffee_cafe', 'name' => 'Coffee Shop / Cafe',
  'voice' => 'Calm, thoughtful, neighborhood-rooted. Talk about beans, roasts, regulars.',
  'hero'  => 'Latte art top-down or a busy counter shot. Headline like the cafe\'s tagline — short and confident.',
  'sections' => 'menu (espresso, drip, pastries — with prices), the roast/beans, our space (interior photos), hours + location, events / open mic (if applicable)',
  'banned' => 'pricing tiers, demo signups, services grid',
  'ctas' => 'Visit us; Order ahead; See the menu',
  'images' => 'baristas pulling shots, latte art, beans being roasted, interior with people working/reading',
  'keywords' => 'coffee,cafe,espresso,latte,roast,brew,barista,beans',
],
[
  'slug' => 'bar_pub', 'name' => 'Bar / Pub',
  'voice' => 'Confident, casual, slightly playful. Local-first. Talk about drinks, the room, the regulars.',
  'hero'  => 'Dim bar interior with warm light, OR a single cocktail close-up. Headline references the place — "The corner of [street]" or a signature drink.',
  'sections' => 'cocktail/beer menu (highlights with photos), happy hour times, events calendar, kitchen menu (if food), hours + location',
  'banned' => 'about-the-founder pages, certifications, services',
  'ctas' => 'Reserve; See cocktails; Tonight\'s events',
  'images' => 'cocktails, bartenders, bottles back-lit, the room at night',
  'keywords' => 'bar,pub,cocktail,beer,tavern,brewery,distillery,lounge,speakeasy',
],
[
  'slug' => 'food_truck', 'name' => 'Food Truck',
  'voice' => 'Fun, off-the-cuff, hungry. Talk about where you\'ll be today.',
  'hero'  => 'The truck itself, OR the hero menu item. Headline names the food + the city.',
  'sections' => 'where we are today / this week (calendar), menu, book us (catering/events), instagram feed, contact',
  'banned' => 'corporate about, FAQ, services grid',
  'ctas' => 'Find the truck; Book for an event; Follow on IG',
  'images' => 'the truck on the street, food close-up, queue lines, the team',
  'keywords' => 'food truck,trailer,mobile,catering truck',
],
[
  'slug' => 'catering', 'name' => 'Catering',
  'voice' => 'Polished, accommodating, detail-oriented. Talk about event sizes and customization.',
  'hero'  => 'Beautifully styled buffet or event-table shot. Headline focused on the occasion ("Wedding catering, done right").',
  'sections' => 'event types (weddings / corporate / private), menus by package, photo gallery from real events, testimonials, request a quote form',
  'banned' => 'walk-in menu, daily specials, online ordering',
  'ctas' => 'Request a quote; See menus; Book a tasting',
  'images' => 'styled event tables, food in trays, servers in motion, real event photos',
  'keywords' => 'catering,catered,event food,wedding food,corporate catering',
],
[
  'slug' => 'law_firm', 'name' => 'Law Firm',
  'voice' => 'Authoritative, calm, plainspoken. No jargon. Avoid "fight"/"warrior" — say "advocate". Talk outcomes, not effort.',
  'hero'  => 'Single confident statement. Photo of senior attorney (head + shoulders) OR a quiet office/courthouse image. NEVER stock gavels or scales-of-justice.',
  'sections' => 'practice areas (3-6 icon cards: estate, family, business, etc.), attorney bios (portrait + bar admissions + 1-paragraph approach), case outcomes (anonymized), client testimonials, consultation CTA, contact',
  'banned' => 'pricing, services-grid-with-checkmarks, free trial, blog teaser',
  'ctas' => 'Schedule a consultation; Free case evaluation; Speak with an attorney',
  'images' => 'attorney portraits (clean bg, mid-frame), office interior, books/desk. NEVER gavel, scales-of-justice clipart, or stock handshakes',
  'keywords' => 'law,attorney,lawyer,legal,counsel,litigation,paralegal,esquire',
],
[
  'slug' => 'accountant', 'name' => 'Accountant / CPA',
  'voice' => 'Trustworthy, precise, calm. Lead with peace of mind, not numbers. Local.',
  'hero'  => 'Clean office portrait OR a soft abstract (no calculators or money-piles). Headline like "Tax season, handled".',
  'sections' => 'services (tax prep, bookkeeping, payroll, advisory), about + credentials, for businesses vs individuals split, client testimonials, schedule a call',
  'banned' => 'pricing per service, blog teaser, services-grid-with-checkmarks',
  'ctas' => 'Schedule a consultation; Get a free review; Call us',
  'images' => 'CPA portrait, office interior, client meetings (from behind), NOT calculators or stacks of money',
  'keywords' => 'accountant,cpa,bookkeeping,tax,payroll,quickbooks,audit',
],
[
  'slug' => 'real_estate', 'name' => 'Real Estate Agent / Brokerage',
  'voice' => 'Confident, local, results-oriented. Lead with neighborhoods + numbers (homes sold, years).',
  'hero'  => 'Beautiful local property shot OR the agent on a porch. Headline names the area — "Selling [city] homes since [year]".',
  'sections' => 'featured listings (cards with photo + price + beds/baths), about agent (portrait + sold count + neighborhoods), client testimonials, sell-with-us / buy-with-us split, contact form',
  'banned' => 'services-grid-with-checkmarks, blog teaser, pricing',
  'ctas' => 'See listings; Get a home valuation; Schedule a tour',
  'images' => 'real local properties, the agent on-site, neighborhood streets, happy clients with keys',
  'keywords' => 'real estate,realtor,broker,homes for sale,property,listing,mls',
],
[
  'slug' => 'insurance', 'name' => 'Insurance Agency',
  'voice' => 'Reassuring, straightforward, local. Avoid jargon — "premium" only when needed.',
  'hero'  => 'Family or local landscape, NOT stock umbrellas. Headline like "Insurance that actually shows up".',
  'sections' => 'coverage types (auto, home, life, business — icon cards), the agent (portrait + years + carriers), claims-day promise, request a quote form, contact',
  'banned' => 'pricing tables, services-grid-with-checkmarks',
  'ctas' => 'Get a quote; Call your agent; File a claim',
  'images' => 'the agent with a client, local landscapes, family scenes, NEVER stock umbrellas',
  'keywords' => 'insurance,agent,coverage,policy,allstate,statefarm,farmers,nationwide',
],
[
  'slug' => 'marketing_agency', 'name' => 'Marketing / Creative Agency',
  'voice' => 'Smart, opinionated, a little cocky. Show work, not buzzwords.',
  'hero'  => 'Bold typographic statement OR a hero piece of their best work. Headline that takes a stand.',
  'sections' => 'work / case studies (large image cards, click-through), services (4-6 cards), about the team (portraits in a grid), client logos, contact / start a project',
  'banned' => 'pricing, blog teaser, FAQ',
  'ctas' => 'Start a project; See the work; Get a brief together',
  'images' => 'real client work as hero pieces, team candids, behind-the-scenes',
  'keywords' => 'agency,marketing,branding,creative,studio,design,advertising,seo,growth',
],
[
  'slug' => 'plumber', 'name' => 'Plumber',
  'voice' => 'Direct, reassuring, no-bs. Local + immediate. They need help RIGHT NOW.',
  'hero'  => 'Phone number gigantic. "24/7 emergency" badge. Real plumber working (not stock).',
  'sections' => 'services (drain, water heater, leaks, repipe — checklist or icon grid), service area (neighborhoods/zips), why us (licensed, insured, years, reviews), Google/Yelp reviews, call CTA repeated',
  'banned' => 'blog, founder story, careers, FAQ',
  'ctas' => 'Call now; Request emergency service; Free estimate',
  'images' => 'technicians on jobs, branded trucks, before/after work, the team in uniform. NEVER stock handshakes',
  'keywords' => 'plumber,plumbing,drain,water heater,leak,pipe,sewer,emergency',
],
[
  'slug' => 'electrician', 'name' => 'Electrician',
  'voice' => 'Trustworthy, safety-first, no-bs. Licensed-and-insured forward.',
  'hero'  => 'Electrician at a panel OR a clean install shot. Phone number prominent. Licensed badge visible.',
  'sections' => 'services (panel upgrades, EV chargers, lighting, generators, troubleshooting), service area, licenses + insurance, reviews, call CTA',
  'banned' => 'blog, founder story',
  'ctas' => 'Call now; Schedule a service; Get a free quote',
  'images' => 'electricians at work, panels, EV chargers, the team',
  'keywords' => 'electrician,electrical,panel,wiring,ev charger,generator,outlet',
],
[
  'slug' => 'hvac', 'name' => 'HVAC / Heating & Cooling',
  'voice' => 'Reliable, comfort-focused. Local + 24/7 emergency framing.',
  'hero'  => 'Tech on a roof or at an outdoor unit. Big phone + emergency badge.',
  'sections' => 'services (install, repair, maintenance plans), service area, financing options, customer reviews, call CTA',
  'banned' => 'blog, careers grid',
  'ctas' => 'Call now; Book a tune-up; Get an estimate',
  'images' => 'techs working on units, branded trucks, smiling customers',
  'keywords' => 'hvac,heating,cooling,air conditioning,furnace,heat pump,ac repair',
],
[
  'slug' => 'roofer_contractor', 'name' => 'Roofer / General Contractor',
  'voice' => 'Solid, experienced, no-bs. Talk about years in business and warranty terms.',
  'hero'  => 'Beautiful finished home/roof OR action shot of a crew. Phone prominent.',
  'sections' => 'services (replacement, repair, gutters, etc.), portfolio (before/after grid), warranty + insurance, financing, reviews, free inspection CTA',
  'banned' => 'blog, founder-paragraph essay',
  'ctas' => 'Free inspection; Get an estimate; Call now',
  'images' => 'finished projects, crews on roofs, branded trucks, before/after pairs',
  'keywords' => 'roofer,roofing,contractor,gutters,siding,remodel,construction',
],
[
  'slug' => 'landscaper', 'name' => 'Landscaper / Lawn Care',
  'voice' => 'Friendly, seasonal, neighborhood-rooted. Beautiful outdoor language.',
  'hero'  => 'Lush finished yard or a designed garden. Sun-soaked.',
  'sections' => 'services (mowing, design, hardscape, irrigation, snow), portfolio gallery, service area map, seasonal package pricing (if applicable), reviews, quote CTA',
  'banned' => 'blog teaser, FAQ',
  'ctas' => 'Get a quote; Schedule a visit; See our work',
  'images' => 'finished yards, crews working, before/after, plants close-up',
  'keywords' => 'landscaper,landscaping,lawn care,mowing,gardening,hardscape,irrigation,snow removal',
],
[
  'slug' => 'cleaning_service', 'name' => 'Cleaning Service',
  'voice' => 'Friendly, dependable, detail-oriented. Lead with "what to expect".',
  'hero'  => 'Sparkling clean room or a smiling crew. NOT a mop close-up.',
  'sections' => 'services (recurring / deep / move-in-out / commercial), what we clean checklist, the team (bonded + insured), pricing or estimate form, reviews',
  'banned' => 'blog, founder essay',
  'ctas' => 'Book now; Get a free quote; Call us',
  'images' => 'clean homes, the crew in branded uniforms, before/after rooms',
  'keywords' => 'cleaning,maid,housekeeping,janitorial,deep clean,move in,commercial cleaning',
],
[
  'slug' => 'dentist', 'name' => 'Dentist',
  'voice' => 'Friendly, calm, family-warm. Avoid clinical scary language.',
  'hero'  => 'Smiling family or a clean modern operatory. NEVER teeth close-ups or X-rays.',
  'sections' => 'services (cleanings, cosmetic, ortho, implants), meet the doctor (portrait + bio), insurance accepted, new patient form / online booking, reviews',
  'banned' => 'blog teaser, pricing per procedure',
  'ctas' => 'Book an appointment; New patient form; Call us',
  'images' => 'smiling patients (full face, not just teeth), the doctor in clinic, modern operatory, the team. NEVER tooth diagrams or close-up teeth',
  'keywords' => 'dentist,dental,orthodontist,teeth,smile,cleaning,implant,invisalign',
],
[
  'slug' => 'chiropractor', 'name' => 'Chiropractor',
  'voice' => 'Welcoming, wellness-forward, pain-relief focused.',
  'hero'  => 'Doc adjusting a patient OR a calm wellness setting. Smiling patient afterward.',
  'sections' => 'conditions treated (back, neck, sciatica, sports, prenatal), techniques, meet the doc, insurance, book online, reviews',
  'banned' => 'pricing tables, blog teaser',
  'ctas' => 'Book a consultation; New patient special; Call us',
  'images' => 'practitioner with patients, calm clinic, wellness imagery',
  'keywords' => 'chiropractor,chiropractic,adjustment,spine,back pain,wellness',
],
[
  'slug' => 'therapist', 'name' => 'Therapist / Counseling',
  'voice' => 'Gentle, non-judgmental, hopeful. No clinical jargon. Talk about feelings clients have, not diagnoses.',
  'hero'  => 'Soft natural light, a chair in a calm room, OR the therapist (warm portrait). Headline that meets people where they are — "You don\'t have to figure it out alone".',
  'sections' => 'who I help / what I help with, approach (modality in plain English), about me (portrait + credentials + personal note), fees + insurance, schedule a free 15-min call',
  'banned' => 'happy stock photos of people jumping, pricing tiers',
  'ctas' => 'Schedule a free 15-min call; Reach out; Send a secure message',
  'images' => 'calm rooms, the therapist (warm + approachable), natural light, NEVER stock thumbs-up smiles',
  'keywords' => 'therapy,therapist,counseling,counselor,psychologist,mental health,anxiety,depression,LMFT,LCSW',
],
[
  'slug' => 'gym_fitness', 'name' => 'Gym / Fitness Studio',
  'voice' => 'Energetic, community-first. Real members, real results.',
  'hero'  => 'Action shot inside the gym — real members, not stock models. Bold headline.',
  'sections' => 'class types / programs, schedule, coaches/trainers (portraits), membership options, free trial / drop-in CTA, member testimonials',
  'banned' => 'stock model abs, fake before/afters',
  'ctas' => 'Start with a free week; Book a class; See the schedule',
  'images' => 'real members training, coaches coaching, the space at peak hours',
  'keywords' => 'gym,fitness,crossfit,training,coach,workout,bootcamp,strength,cardio',
],
[
  'slug' => 'yoga_pilates', 'name' => 'Yoga / Pilates Studio',
  'voice' => 'Calm, grounded, inclusive. Less hustle, more presence.',
  'hero'  => 'Quiet pose, candle-lit studio, OR teacher mid-cue. Soft light.',
  'sections' => 'class types (vinyasa, yin, reformer, mat), schedule, teachers, intro offer, FAQ for new students',
  'banned' => 'aggressive sales banners, before/after photos',
  'ctas' => 'Try your first class free; Book a class; See the schedule',
  'images' => 'students in poses, teachers cueing, the studio interior with natural light',
  'keywords' => 'yoga,pilates,reformer,vinyasa,meditation,mindfulness,studio',
],
[
  'slug' => 'hair_salon', 'name' => 'Hair Salon',
  'voice' => 'Stylish, personable, current. Show the work.',
  'hero'  => 'Hero portrait of a finished cut/color OR the chic salon interior.',
  'sections' => 'services + pricing menu, meet the stylists (portraits + specialties), before/after gallery, book online, hours + address',
  'banned' => 'corporate stat strip, blog teaser',
  'ctas' => 'Book now; See pricing; Meet the stylists',
  'images' => 'styled hair (real clients), stylists at work, the salon interior',
  'keywords' => 'hair,salon,stylist,cut,color,balayage,highlights,blowout',
],
[
  'slug' => 'barber', 'name' => 'Barber Shop',
  'voice' => 'Direct, masculine, neighborhood-rooted. Old-school + modern.',
  'hero'  => 'Sharp cut close-up OR the barber shop chair under warm light.',
  'sections' => 'cuts menu + prices, the barbers (portraits + how-long-cutting), book online, hours + address, gallery of cuts',
  'banned' => 'aggressive sales banners',
  'ctas' => 'Book a cut; See the barbers; Walk-ins welcome',
  'images' => 'finished cuts, barbers at chairs, the shop interior with leather + brass + tile',
  'keywords' => 'barber,barbershop,fade,cut,haircut,beard,shave',
],
[
  'slug' => 'med_spa', 'name' => 'Med Spa / Aesthetics',
  'voice' => 'Polished, science-backed, results-focused. Avoid hype.',
  'hero'  => 'Clean treatment room OR a beautifully-lit portrait of a real client.',
  'sections' => 'services (botox, fillers, lasers, facials), the providers (credentialed), before/afters, financing, book a consultation',
  'banned' => 'fake "before/after" stock photos, exaggerated claims',
  'ctas' => 'Book a free consultation; Save with our membership; See services',
  'images' => 'real before/afters, the providers in clinical setting, calm rooms',
  'keywords' => 'med spa,medspa,botox,filler,laser,aesthetics,injectables,facial',
],
[
  'slug' => 'boutique', 'name' => 'Boutique / Retail Store',
  'voice' => 'Curated, point-of-view, neighborhood-rooted.',
  'hero'  => 'Hero product flatlay OR a vibe shot of the store interior.',
  'sections' => 'featured products (4-6 cards with photo + price), shop categories, the store/about, location + hours, newsletter signup',
  'banned' => 'corporate metrics, blog teaser',
  'ctas' => 'Shop now; Visit the store; Join the list',
  'images' => 'styled product flatlays, the store interior, model-worn pieces',
  'keywords' => 'boutique,shop,store,apparel,jewelry,gifts,home goods',
],
[
  'slug' => 'auto_repair', 'name' => 'Auto Repair Shop',
  'voice' => 'Trustworthy, no-upsell. Talk about being honest with people\'s cars.',
  'hero'  => 'Tech under a car, OR a clean shop bay. Phone + "ASE certified" badge.',
  'sections' => 'services (oil, brakes, tires, diagnostics, AC, transmissions), specialties (foreign / domestic / EVs), the techs, reviews, schedule a service form',
  'banned' => 'blog, generic stock auto images',
  'ctas' => 'Schedule a service; Get an estimate; Call us',
  'images' => 'real techs at work, the shop bays, branded shop, real customer cars',
  'keywords' => 'auto repair,mechanic,car repair,oil change,brakes,transmission,tire,ase',
],
[
  'slug' => 'wedding_venue', 'name' => 'Wedding Venue / Event Space',
  'voice' => 'Romantic, elegant, but practical (capacity, dates, in-house vs vendor).',
  'hero'  => 'Beautifully lit hero shot of the space at golden hour, set for an event.',
  'sections' => 'the space (multiple rooms + capacities), photo gallery of real weddings, what\'s included, available dates, schedule a tour CTA, real-couple testimonials',
  'banned' => 'pricing-per-head tables (gate this behind tour), aggressive sales',
  'ctas' => 'Schedule a tour; Check available dates; See the space',
  'images' => 'real weddings at the venue, the empty space styled, exterior at golden hour',
  'keywords' => 'wedding venue,event space,reception,banquet,ballroom,barn,estate',
],
[
  'slug' => 'photographer', 'name' => 'Photographer / Videographer',
  'voice' => 'Confident, story-first, personable. Let the work do the talking.',
  'hero'  => 'A single stunning image from a recent shoot. No words on the image.',
  'sections' => 'portfolio grid (large, clickable categories: weddings / portraits / brands / events), about me (warm portrait + 2-paragraph story), packages, inquire / contact form, testimonials',
  'banned' => 'blog teaser as a main section, watermarked images',
  'ctas' => 'Inquire; See packages; View the portfolio',
  'images' => 'their own work as hero pieces, BTS of them shooting, a warm portrait of themselves',
  'keywords' => 'photographer,photography,videographer,videography,wedding photo,portrait,brand photo',
],
];
